import antdData from 'antd/lib/locale-provider/en_US'
import localeData from 'react-intl/locale-data/en'

const messages = {
  'topBar.profileMenu.hello': 'Hello',
  'topBar.profileMenu.billingPlan': 'Billing Plan',
  'topBar.profileMenu.role': 'Role',
  'topBar.profileMenu.email': 'Email',
  'topBar.profileMenu.phone': 'Phone',
  'topBar.profileMenu.editProfile': 'Edit Profile',
  'topBar.profileMenu.logout': 'Logout',

  'footer.copyright': 'Copyright Panamax Inc. | Powered By',

  'login.form.prefix': 'login',
  'login.username': 'Username',
  'login.password': 'Password',
  'login.title.message': 'Please log in',
  'login.failed': 'Log In Failed',
  'login.failed.description': 'Incorrect username or password',
  'login.error.username': 'Please input user name',
  'login.error.password': 'Please input your password',
  'login.button.label': 'Login',
  'login.rememberme.label': 'Remember Me',
  'login.forgotpassword.link': 'Forgot Password ?',

  'forgot.error.username': 'Please input user name',
  'forgot.username.label': 'Restore Password',
  'forgot.title.message': 'Please log in',
  'forgot.backtologin.link': 'Back to Login',
  'forgot.button.label': 'Restore Password',

  'global.breadcrumbs.view.heading': 'View',
  'global.breadcrumbs.detail.heading': 'Detail',
  'global.breadcrumbs.edit.heading': 'Edit',
  'global.breadcrumbs.update.heading': 'Update',
  'global.breadcrumbs.add.heading': 'Add',
  'global.breadcrumbs.create.heading': 'Create',
  'global.breadcrumbs.list.heading': 'list',
  'global.breadcrumbs.grid.heading': 'Grid',

  'operationbar.button.add': 'Add',
  'operationbar.button.edit': 'Edit',
  'operationbar.button.add.service': 'Add Service',
  'operationbar.button.delete': 'Delete',
  'operationbar.button.back': 'Back',
  'operationbar.button.save': 'Save',
  'operationbar.button.cancel': 'Cancel',
  'operationbar.button.export': 'Export',
  'operationbar.button.log': 'Log',
  'operationbar.button.view': 'View',

  'module.name.accesschannel': 'Access Channel',
  'module.name.operation': 'Operation',
  'module.name.systemoperatorentity': 'System Operator Entity',
  'module.name.onboarding': 'On Boarding',
  'module.name.profilemanagement': 'Profile Management',
  'module.name.treemanagement': 'Tree Management',
  'module.name.product': 'Product',
  'module.name.provider': 'Provider',
  'module.name.vendor': 'Vendor',
  'module.name.vendorproduct': 'Vendor Product',
  'module.name.settings': 'Settings',
  'module.name.usermanagement': 'User Management',
  'module.name.user': 'User',
  'module.name.department': 'Department',
  'module.name.role': 'Role',
  'module.name.gismaster': 'GIS Master',
  'module.name.country': 'Country',
  'module.name.state': 'State',
  'module.name.currencymanagement': 'Currency Management',
  'module.name.exchangerate': 'Exchange Rate',
  'module.name.globalconfiguration': 'Global Configuration',
  'module.name.userentity': 'User Entity',
  'module.name.businessentity': 'Business Entity',
  'module.name.unit': 'Unit',
  'module.name.dkycmaster': 'DKYC Master',
  'module.name.kyclevel': 'KYC Level',
  'module.name.kycfield': 'KYC Field',
  'module.name.userkycfieldgroup': 'User KYC Field Group',
  'module.name.businessconfiguration': 'Business Configuration',
  'module.name.serviceprofileentities': 'Service Profile Entities',

  'module.name.services': 'Services',
  'module.name.alertnotification': 'Alert Notification',
  'module.name.support': 'Support',

  'module.name.unitcreditpolicy': 'Unit Credit Policy',
  'module.name.counter': 'Counter',
  'module.name.report': 'Report',
  'module.name.mobiview': 'MobiView',

  'module.name.agent': 'Agent',
  'module.name.customer': 'Customer',
  'module.name.merchant': 'Merchant',
  'module.name.bank': 'Bank',
  'module.name.coc': 'COC',
  'module.name.enterprice': 'Enterprise',
  'module.name.trustaccount': 'Trust Account',

  'module.name.Role': 'Role',

  'module.name.platformconfiguration': 'Platform Configuration',
  'module.name.administration': 'Administration',
  'module.name.parameter': 'Parameter',
  'module.name.kyc': 'KYC',
  'module.name.usercategory': 'User Category',
  'module.name.businesszone': 'Business Zone',
  'module.name.wallet': 'Wallet',
  'module.name.pouch': 'Pouch',
  'module.name.rule': 'Rule',
  'module.name.productgroup': 'Product Group',
  'module.name.notificationtemplate': 'Notification Template',
  'module.name.exchangeratemanager': 'Exchange Rate Manager',
  'module.name.vendormanagement': 'Vendor Management',
  'module.name.servicevendor': 'Service Vendor',
  'module.name.technicalvendor': 'Technical Vendor',
  'module.name.notificationmanagement': 'Notification Management',
  'module.name.notification': 'Notification',
  'module.name.productmanagement': 'Product Management',
  'module.name.serviceprofile': 'Service Profile',

  'module.name.emoney': 'Emoney',
  'module.name.metrics': 'Metrics',
  'module.name.health': 'Health',
  'module.name.configuration': 'Configuration',
  'module.name.audits': 'Audits',
  'module.name.log': 'Log',
  'module.name.api': 'API',

  'accesschannel.name': 'Name',
  'accesschannel.label.add': 'Add Access Channel',
  'accesschannel.label.edit': 'Edit Access Channel',
  'accesschannel.label.view': 'View Access Channel',
  'accesschannel.description': 'Description',
  'accesschannel.externalid': 'External ID',
  'accesschannel.status': 'Status',
  'accesschannel.label.createdby': 'Created By',
  'accesschannel.label.createddatetime': 'Created Time',
  'accesschannel.label.updatedby': 'Updated By',
  'accesschannel.label.updateddatetime': 'Updated Time',
  'accesschannel.status.active': 'Active',
  'accesschannel.status.inactive': 'Inactive',

  'accesschannel.grid.srno': 'Sr. No.',
  'accesschannel.grid.view': 'View',
  'accesschannel.grid.id': 'ID',
  'accesschannel.grid.name': 'Name',
  'accesschannel.grid.description': 'Description',
  'accesschannel.grid.externalid': 'External ID',
  'accesschannel.grid.updatedby': 'Updated By',
  'accesschannel.grid.updateddatetime': 'Updated Time',
  'accesschannel.grid.status': 'Status',

  'accesschannel.error.name.minimum': 'Minimum 2 character required',
  'accesschannel.error.name.maximum50': 'Maximum 50 character required',
  'accesschannel.error.name.maximum200': 'Maximum 200 character required',
  'accesschannel.error.name': 'Please enter valid Name',
  'accesschannel.error.description': 'Please enter valid Description',
  'accesschannel.error.externalid': 'Please enter valid Externalid',
  'accesschannel.error.status': 'Please enter valid Status',
  'accesschannel.error.delete': 'Error occurred while deleting Access Channel',

  'accesschannel.success.add': 'Access channel Added Successfully',
  'accesschannel.success.edit': 'Access channel updated Successfully',
  'accesschannel.success.delete': 'Access channel deleted Successfully',
  'accesschannel.fail.delete':
    'This Access channel has been assigned more than one module, Please remove it and try again',
  'accesschannel.delete.confirm.message': 'Are you sure, You want to delete ?',
  'accesschannel.head.popup.add': 'Alert Add',
  'accesschannel.head.popup.edit': 'Update data',
  'accesschannel.head.popup.delete': 'Delete data',

  'provider.grid.srno': 'Sr. No.',
  'provider.grid.view': 'View',
  'provider.grid.id': 'ID',
  'provider.grid.name': 'Name',
  'provider.grid.externalid': 'External ID',
  'provider.grid.createddate': 'Created Date',
  'provider.grid.updateddate': 'Updated Date',
  'provider.grid.status': 'Status',

  'provider.name': 'Name',
  'provider.externalid': 'External ID',
  'provider.status': 'Status',
  'provider.status.active': 'Active',
  'provider.status.inactive': 'Inactive',

  'provider.error.name': 'Please Input Name',
  'provider.error.description': 'Please Input Description',
  'provider.error.externalid': 'Please Input Externalid',
  'provider.error.status': 'Please Input Status',

  'provider.success.add': 'Provider Added Successfully',
  'provider.success.edit': 'Provider updated Successfully',
  'provider.success.delete': 'Provider deleted Successfully',
  'provider.head.popup.add': 'Alert Add',
  'provider.head.popup.edit': 'Update data',
  'provider.head.popup.delete': 'Delete data',

  // Country
  'country.name': 'Name',
  'country.countryName': 'Country Name',
  'country.countryCode_2': 'Currency Code',
  'country.dilalingCode': 'Dialing Code',
  'country.maxnnlength': 'Max National Number Length',
  'country.minnnlength': 'Min National Number Length',

  'country.grid.srno': 'Sr. No.',
  'country.grid.view': 'View',
  'country.grid.id': 'ID',
  'country.grid.abbreviationCode2': 'Abbreviation Code(2)',
  'country.grid.abbreviationCode3': 'Abbreviation Code(3)',
  'country.grid.countryName': 'Country Name',
  'country.grid.diallingCode': 'Dialling Code',
  'country.grid.minimumNumber': 'Min National Number Length',
  'country.grid.maximumNumber': 'Max National Number Length',
  'country.grid.updateddate': 'Updated Date & Time',
  'country.grid.updatedby': 'Updated by',

  'country.add.abbreviationcode2': 'Abbreviation Code(2)',
  'country.add.abbreviationcode3': 'Abbreviation Code(3)',
  'country.add.dailling.code': 'Dialling Code',
  'country.add.currency.code': 'Currency Code',
  'country.add.currency.code.india': 'India',
  'country.add.currency.code.uae': 'UAE',

  'country.edit.abbreviationcode2': 'Abbreviation Code(2)',
  'country.edit.abbreviationcode3': 'Abbreviation Code(3)',
  'country.edit.dailling.code': 'Dialling Code',

  'country.success.add': 'Country Added Successfully',
  'country.success.edit': 'Country updated Successfully',
  'country.success.delete': 'Country deleted Successfully',
  'country.delete.confirm.message': 'Are you sure, You want to delete ?',

  'country.head.popup.add': 'Alert Add',
  'country.head.popup.edit': 'Update data',
  'country.head.popup.delete': 'Delete data',
  'country.error.countrycode2': 'Maximum 2 characters allowed',
  'country.error.countrycode3': 'Maximum 3 characters allowed',
  'country.error.countrydialcode10': 'Maximum 10 characters allowed',

  'country.label.add': 'Add Country',
  'country.label.edit': 'Edit Country',
  'country.label.view': 'View Country',

  'country.error.countryCode': 'Please Input Country Code',
  'country.error.dilalingCode': 'Please Input Dialing Code',
  'country.error.countryCode2CharMaxLength': 'Please Input Maximum Two Characters',
  'country.error.countryCode3CharMaxLength': 'Please Input Maximum Three Characters',
  'country.error.country.name': 'Please Input Country Name',
  'country.error.abbreviation.code2': 'Please Input Abbreviation Code(2)',
  'country.error.abbreviation.code3': 'Please Input Abbreviation Code(3)',
  'country.error.dialling.code': 'Please Input Dialling Code',
  'country.error.currency.code': 'Please Input Currency Code',

  'usercategory.grid.view': 'View',
  'usercategory.grid.srno': 'Sr No',
  'usercategory.grid.name': 'Name',
  'usercategory.grid.updatedby': 'Updated By',
  'usercategory.grid.updateddate': 'Updated Date & Time',
  'usercategory.grid.status': 'Status',

  'usercategory.label.view': 'User Category View',
  'usercategory.label.name': 'Name',
  'usercategory.label.add': ' User Category Add',
  'usercategory.label.edit': ' User Category Edit',
  'usercategory.label.visibility': 'Status',
  'usercategory.label.categorytype': 'Category Type',
  'usercategory.label.visibilityactive': 'Active',
  'usercategory.label.visibilityinactive': 'Inactive',
  'usercategory.label.updateddatetime': 'Updated Date & Time',
  'usercategory.label.createddatetime': 'Created Date & Time',
  'usercategory.label.createdby': 'Created By',
  'usercategory.label.updatedby': 'Updated By',
  'usercategory.label.description': 'Description',
  'usertype.label.select.placeholder': 'Select User Type',

  'usercategory.error.name': 'Please enter valid name',
  'usercategory.error.categorytype': 'Please select category type',
  'usercategory.error.description': 'Please enter valid Description',
  'usercategory.error.nameExists': 'Name already Exists',
  'usercategory.error.name.minimum': 'Minimum 2 character required',
  'usercategory.error.name.maximum50': 'Maximum 50 character required',
  'usercategory.error.name.maximum200': 'Maximum 200 character required',

  'usercategory.success.add': 'User category added successfully',
  'usercategory.success.edit': 'User category updated successfully',
  'usercategory.success.delete': 'User category deleted successfully',
  'usercategory.error.delete': 'Error occured while deleting User category',
  'usercategory.delete.confirm.message': 'Are you sure, You want to delete ?',
  'usercategory.head.popup.add': 'Data added',
  'usercategory.head.popup.edit': 'Data updated',
  'usercategory.head.popup.delete': 'Data deleted',

  'userentity.delete.description': 'description',
  'userentity.grid.view': 'View',
  'userentity.grid.srno': 'Sr No',
  'userentity.grid.name': 'User Entity Name',
  'userentity.grid.description': 'Description',
  'userentity.grid.externalid': 'External ID',
  'userentity.grid.entitytype': 'User Entity Type',
  'userentity.grid.updatedby': 'Updated By',
  'userentity.grid.updateddate': 'Updated Date & Time',
  'userentity.grid.status': 'Status',
  'userentity.label.userEntityType1': 'Wallet',
  'userentity.label.userEntityType2': 'Non-wallet',

  'userentity.label.view': 'User Entity View',
  'userentity.label.name': 'User Entity Name',
  'userentity.label.add': ' User Entity Add',
  'userentity.label.edit': ' User Entity Edit',
  'userentity.label.externalid': 'External ID',
  'userentity.label.description': 'Description',
  'userentity.label.userentitytype': 'User Entity Type',
  'userentity.label.userentitytype1': 'Wallet',
  'userentity.label.userentitytype2': 'Non-Wallet',
  'userentity.label.visibility': 'Status',
  'userentity.label.visibilityactive': 'Active',
  'userentity.label.visibilityinactive': 'Inactive',
  'userentity.label.updateddatetime': 'Updated Date & Time',
  'userentity.label.createddatetime': 'Created Date & Time',
  'userentity.label.createdby': 'Created By',
  'userentity.label.updatedby': 'Updated By',

  'userentity.error.name': 'Please enter valid name',
  'userentity.error.nameExists': 'Entity Name already exists',
  'userentity.error.nameexists': 'Name already Exists',
  'userentity.error.name.minimum': 'Minimum 2 character required',
  'userentity.error.name.maximum50': 'Maximum 50 character required',
  'userentity.error.name.maximum200': 'Maximum 200 character required',
  'userentity.error.description': 'Please enter valid description',
  'userentity.error.userentitytype': 'Please enter user enity type',

  'userentity.success.add': 'User entity added successfully',
  'userentity.success.edit': 'User entity updated successfully',
  'userentity.success.delete': 'User entity deleted successfully',
  'userentity.delete.confirm.message': 'Are you sure, You want to delete ?',
  'userentity.head.popup.add': 'Data added',
  'userentity.head.popup.edit': 'Data updated',
  'userentity.head.popup.delete': 'Data deleted',

  'kyclevel.name': 'Name',
  'kyclevel.description': 'Description',
  'kyclevel.externalid': 'External ID',
  'kyclevel.status': 'Status',
  'kyclevel.status.active': 'Active',
  'kyclevel.status.inactive': 'Inactive',
  'kyclevel.createddate': 'Created Date & Time',
  'kyclevel.updateddate': 'Updated Date & Time',
  'kyclevel.createdby': 'Created By',
  'kyclevel.updatedby': 'Updated By',

  'kyclevel.grid.view': 'View',
  'kyclevel.grid.id': 'ID',
  'kyclevel.grid.srno': 'Sr.No',
  'kyclevel.grid.name': 'Name',
  'kyclevel.grid.description': 'Description',
  'kyclevel.grid.externalid': 'External ID',
  'kyclevel.grid.updatedby': 'Updated By',
  'kyclevel.grid.visibility': 'Status',
  'kyclevel.grid.updateddate': 'Updated Date & Time',
  'kyclevel.error.name': 'Please enter valid Name',
  'kyclevel.error.description': 'Please enter valid Description',
  'kyclevel.error.status': 'Please Select Status',
  'kyclevel.error.name.minimum': 'Minimum 2 character required',
  'kyclevel.error.name.maximum50': 'Maximum 50 character required',
  'kyclevel.error.name.maximum200': 'Maximum 200 character required',

  'kyclevel.success.add': 'Kyclevel Added Successfully',
  'kyclevel.success.edit': 'Kyclevel updated Successfully',
  'kyclevel.success.delete': 'Kyclevel deleted Successfully',
  'kyclevel.delete.confirm.message': 'Are you sure, You want to delete ?',
  'kyclevel.head.popup.add': 'Alert Add',
  'kyclevel.head.popup.edit': 'Update data',
  'kyclevel.head.popup.delete': 'Delete data',

  // Services
  'services.name': 'Name',
  'services.description': 'Description',
  'services.externalid': 'External ID',
  'services.status': 'Status',
  'services.status.active': 'Active',
  'services.status.inactive': 'Inactive',
  'services.label.view': 'View Services',
  'services.label.edit': 'Edit Services',
  'services.label.servicetype': 'Service Type',
  'services.createdBy': 'Created By',
  'services.createdDate': 'Created Time',
  'services.updatedBy': 'Updated By',
  'services.updatedDate': 'Updated Time',

  'services.grid.view': 'View',
  'services.grid.id': 'Sr No.',
  'services.grid.name': 'Name',
  'services.grid.description': 'Description',
  'services.grid.externalid': 'External ID',
  'services.grid.createdDate': 'Created Date',
  'services.grid.updatedDate': 'Updated Date',
  'services.grid.validFromDate': 'Valid From Date',
  'services.grid.validToDate': 'Valid To Date',
  'services.grid.lastUpdateDate': 'Updated Time',
  'services.grid.updatedBy': 'Updated By',
  'services.grid.status': 'Status',

  'services.error.name': 'Please enter valid Name.',
  'services.error.description': 'Please enter valid Description',
  'services.error.externalid': 'Please enter valid Externalid',
  'services.error.status': 'Please Input Status',
  'services.error.name.minsize': 'Minimum 2 character required ',
  'services.error.name.maxsize': 'Maximum 50 character required',
  'services.error.servicetype': 'Please select service type',
  'services.error.description.minsize': 'Minimum 2 character required',
  'services.error.description.maxsize': 'Maximum 200 character required',

  'services.delete.message': 'Are you sure, you want to delete this ?',
  'services.fail.delete':
    'This Services has been assigned more than one module, Please remove it and try again',
  'services.success.add': 'Services Added Successfully',
  'services.success.edit': 'Services updated Successfully',
  'services.success.delete': 'Services deleted Successfully',
  'services.head.popup.add': 'Alert Add',
  'services.head.popup.edit': 'Update data',
  'services.head.popup.delete': 'Delete data',

  'unit.grid.srno': 'Sr. No.',
  'unit.grid.view': 'View',
  'unit.grid.id': 'ID',
  'unit.grid.name': 'Unit Name',
  'unit.grid.externalid': 'External ID',
  'unit.grid.unitbehaviour': 'Behaviour',
  'unit.grid.unittype': 'Unit Type',
  'unit.grid.updateddate': 'Updated Date',
  'unit.grid.updatedby': 'Updated By',
  'unit.grid.status': 'Status',

  'unit.name': 'Name',
  'unit.externalid': 'External ID',
  'unit.status': 'Status',
  'unit.status.active': 'Active',
  'unit.status.inactive': 'Inactive',
  'unit.description': 'Description',
  'unit.behaviour': 'Behaviour',
  'unit.unittype': 'Unit Type',
  'unit.unittype.monatary': 'Monatary',
  'unit.unittype.nonmonatary': 'Non-Monatary',
  'unit.behaviour.disbursement': 'Disbursement',
  'unit.behaviour.collection': 'Collection',

  'unit.createdBy': 'Created By',
  'unit.createdDate': 'Created Time',
  'unit.updatedBy': 'Updated By',
  'unit.updatedDate': 'Updated Time',

  'unit.success.add': 'Unit Added Successfully',
  'unit.success.edit': 'Unit updated Successfully',
  'unit.success.delete': 'Unit deleted Successfully',
  'unit.delete.message': 'Are you sure you want to delete this?',
  'unit.head.popup.add': 'Alert Add',
  'unit.head.popup.edit': 'Update data',
  'unit.head.popup.delete': 'Delete data',

  'unit.error.name.minimum': 'Minimum 2 character required',
  'unit.error.name.maximum50': 'Maximum 50 character required',
  'unit.error.name.maximum200': 'Maximum 200 character required',

  'unit.error.description.minimum': 'Minimum 2 character required',
  'unit.error.description.maximum50': 'Maximum 50 character required',
  'unit.error.description.maximum200': 'Maximum 200 character required',

  'unit.error.name': 'Please Input Name',
  'unit.error.description': 'Please Input Description',
  'unit.error.externalid': 'Please Input Externalid',
  'unit.error.status': 'Please Input Status',
  'unit.error.unittype': 'Please Select Unit Type',
  'unit.error.behaviour': 'Please Select Behaviour',
  'unit.fail.delete':
    'This unit has been assigned more than one module, Please remove it and try again',

  'state.grid.srno': 'Sr. No.',
  'state.grid.view': 'View',
  'state.grid.id': 'ID',
  'state.grid.state': 'State',
  'state.grid.abbreviationcode': 'Abbreviation Code',
  'state.grid.country': 'Country',
  'state.grid.updateby': 'Update By',
  'state.grid.updatetime': 'Updated Time',
  'state.country.name': 'Country',

  'state.success.add': 'State Added Successfully',
  'state.success.edit': 'State updated Successfully',
  'state.success.delete': 'State deleted Successfully',

  'state.head.popup.add': 'Alert Add',
  'state.head.popup.edit': 'Update data',
  'state.head.popup.delete': 'Delete data',

  'state.error.countryName': 'Please Input Countrys Name',
  'state.error.stateName': 'Please Input State Name',
  'state.error.statecode': 'Please Input Abbreviation Code',
  'state.delete.confirm.message': 'Are you sure, you want to delete this ?',
  'state.error.name.minimum': 'Minimum 2 character required',
  'state.error.name.maximum': 'Maximum 50 character required',
  'state.error.name.maximum10': 'Maximum 10 character required',

  'state.label.country': 'Country',
  'state.label.state': 'State',
  'state.label.abbreviationcode': 'Abbreviation Code',
  'state.label.createdby': 'Created By',
  'state.label.createddatetime': 'Created Time',
  'state.label.updateby': 'Update By',
  'state.label.updatetime': 'Updated Time',

  // Department
  'department.departmentName': 'Department',
  'department.externalID': 'External ID',
  'department.description': 'Description',
  'department.status': 'Status',
  'department.status.active': 'Active',
  'department.status.inactive': 'Inactive',
  'department.updatedBy': 'Last Updated By',
  'department.lastUpdateDate': 'Updated Date & Time',
  'department.createdby': 'Created By',
  'department.createddatetime': 'Created Time',
  'department.grid.srno': 'Sr. No.',
  'department.grid.view': 'View',
  'department.grid.id': 'ID',
  'department.grid.departmentName': 'Department Name',
  'department.grid.externalId': 'External ID',
  'department.grid.description': 'Description',
  'department.grid.createddate': 'Created Date',
  'department.grid.updateddate': 'Updated Date & Time',
  'department.error.departmentName': 'Please Input Department Name',
  'department.error.description': 'Please Input Description',
  'department.error.externalId': 'Please Input External ID',
  'department.error.departmentName.MinMaxLength':
    'Please Input Minimum 2 and Maximum 50 Characters',
  'department.error.departmentDescription.MinMaxLength':
    'Please Input Minimum 2 and Maximum 200 Characters',
  'department.success.add': 'Department Added Successfully',
  'department.success.edit': 'Department updated Successfully',
  'department.success.delete': 'Department deleted Successfully',
  'department.head.popup.add': 'Add data',
  'department.head.popup.edit': 'Update data',
  'department.head.popup.delete': 'Delete data',
  'department.error.nameExists': 'Department Name already exists',
  'department.delete.confirm.message': 'Are you sure, you want to delete this ?',

  // Role
  'role.grid.srno': 'Sr. No.',
  'role.grid.view': 'View',
  'role.grid.id': 'ID',
  'role.grid.name': 'Role Name',
  'role.grid.description': 'Description',
  'role.grid.updateddatetime': 'Updated Date & Time',
  'role.grid.updatedby': 'Updated By',
  'role.grid.status': 'Status',

  'role.name': 'Name',
  'role.externalid': 'ExternalId',
  'role.description': 'Description',
  'role.status': 'Status',
  'role.createdby': 'Created By',
  'role.createddatetime': 'Created Date & Time',
  'role.updatedby': 'Updated By',
  'role.updateddatetime': 'Updated Date & Time',
  'role.label.usercategory': 'User Category',
  'role.label.role': 'Role Name',
  'role.label.add': 'Add Role',
  'role.label.edit': 'Edit Role',
  'role.label.view': 'View Role',

  'role.error.name': 'Please enter valid Role Name',
  'role.error.name.minimum2': 'Minimum 2 character required',
  'role.error.name.maximum50': 'Maximum 50 character required',

  'role.error.description': 'Please enter valid Description',
  'role.error.description.minsize2': 'Minimum 2 character required',
  'role.error.description.maxsize200': 'Maximum 200 character required',
  'role.status.active': 'Active',
  'role.status.inactive': 'Inactive',

  'role.success.add': 'Role Added Successfully',
  'role.success.edit': 'Role Updated Successfully',
  'role.success.delete': 'Role Deleted Successfully',
  'role.head.popup.add': 'Alert Add',
  'role.head.popup.edit': 'Update data',
  'role.head.popup.delete': 'Delete data',
  'role.delete.message': 'Are you sure, you want to delete this ?',

  'ucp.title.add': 'Add Unitcreditpolicy',
  'ucp.title.edit': 'Edit Unitcreditpolicy',

  'ucp.grid.view': 'View',
  'ucp.grid.srno': 'SR No.',
  'ucp.grid.name': 'Name',
  'ucp.grid.updatedby': 'Updated By',
  'ucp.grid.updatedtime': 'Updated Time',
  'ucp.grid.status': 'Status',
  'unit.label.view': 'View Unit',
  'ucp.placeholder.unittype': 'Please select unit type',
  'ucp.label.name': 'Name',
  'ucp.label.unittype': 'Unit Type',
  'ucp.label.description': 'Description',
  'ucp.label.credittype': 'Credit Type',
  'ucp.label.credittype1': 'Absolute',
  'ucp.label.credittype2': 'Percentage',
  'ucp.label.crediton': 'Credit On',
  'ucp.label.crediton1': 'Amount',
  'ucp.label.crediton2': 'Unit',
  'ucp.label.crediton3': 'Amount + Unit',
  'ucp.label.unit': 'Unit',
  'ucp.label.value': 'Value',
  'ucp.label.status': 'Status',
  'ucp.label.createdby': 'Created By',
  'ucp.label.createdtime': 'Created Time',
  'ucp.label.updatedby': 'Updated By',
  'ucp.label.updatedtime': 'Updated Time',
  'ucp.label.externalid': 'External ID',
  'ucp.status.active': 'Active',
  'ucp.status.inactive': 'Inactive',

  'ucp.error.name': 'Please enter valid name',
  'ucp.error.name.minimum2': 'Minimum 2 character required',
  'ucp.error.name.maximum50': 'Maximum 50 character allowed',
  'ucp.error.value.minimum2': 'Minimum 2 character required',
  'ucp.error.value.maximum20': 'Maximum 20 character allowed',
  'ucp.error.unittype': 'Unit type is required',
  'ucp.error.credittype': 'Credit type is required',
  'ucp.error.unit': 'Unit is required',
  'ucp.error.value': 'Value is required',
  'ucp.error.crediton': 'Credit on is required',
  'ucp.error.description': 'Please enter valid description',
  'ucp.delete.confirm.message': 'Are you sure, You want to delete ?',
  'ucp.success.add': 'Unit Credit Policy added successfully',
  'ucp.success.edit': 'Unit Credit Policy updated successfully',
  'ucp.success.delete': 'Unit Credit Policy deleted successfully',
  'ucp.fail.delete': 'Error in deletion of UCP',

  // Rule
  'rule.grid.view': 'View',
  'rule.grid.srno': 'Sr. No.',
  'rule.grid.name': 'Name',
  'rule.grid.description': 'Description',
  'rule.grid.updateddatetime': 'Updated Date & Time',
  'rule.grid.updatedby': 'Updated By',
  'rule.search.name': 'Name',

  'rule.name': 'Name',
  'rule.description': 'Description',
  'rule.expression': 'Expression',
  'rule.createdby': 'CreatedBy',
  'rule.createdtime': 'Created Time',
  'rule.updatedby': 'Updated By',
  'rule.updatedtime': 'Updated Time',

  'rule.error.name': 'Please enter valid Name',
  'rule.error.name.minimum2': 'Minimum 2 character required',
  'rule.error.name.maximum50': 'Maximum 50 character required',

  'rule.error.description': 'Please enter valid Description',
  'rule.error.name.maximum200': 'Maximum 200 character required',
  'rule.error.expression': 'Please enter valid Expression',

  'rule.success.add': 'Rule Added Successfully',
  'rule.success.edit': 'Rule updated Successfully',
  'rule.success.delete': 'Rule deleted Successfully',
  'rule.delete.confirm.message': 'Are you sure, You want to delete ?',
  'rule.head.popup.add': 'Alert Add',
  'rule.head.popup.edit': 'Update data',
  'rule.head.popup.delete': 'Delete data',

  'rule.label.add': 'Add Rule',
  'rule.label.edit': 'Edit Rule',
  'rule.label.view': 'View Rule',
  'error.InvalidExpression': 'Invalid Expression',

  // Counter
  'counter.grid.view': 'View',
  'counter.grid.srno': 'Sr. No.',
  'counter.grid.name': 'Conuter Name',
  'counter.grid.externalid': 'External ID',
  'counter.grid.counton': 'Conut On',
  'counter.grid.resettype': 'Reset Type',
  'counter.grid.updateddatetime': 'Updated Date & Time',
  'counter.grid.updatedby': 'Updated By',
  'counter.grid.status': 'Status',

  // view label
  'conuter.success.add': 'Counter Added Successfully',
  'conuter.success.edit': 'Counter Updated Successfully',
  'conuter.success.delete': 'Counter Deleted Successfully',

  'conuter.head.popup.add': 'Alert Add',
  'conuter.head.popup.edit': 'Update data',
  'conuter.head.popup.delete': 'Delete data',

  'conuter.delete.message': 'Are you sure, you want to delete this ?',
  'counter.delete.confirm.message': 'Are you sure, You want to delete ?',
  'counter.error.delete': 'Error occurred while deleting Counter',

  'counter.label.view': 'View',
  'counter.label.name': 'Name',
  'counter.label.externalid': 'External ID',
  'counter.label.description': 'Description',
  'counter.label.counton': 'Count On',
  'counter.label.counterlimit': 'Counter Limit',
  'counter.label.resettype': 'Reset Type',
  'counter.label.dayoftheweek': 'Day of the week',
  'counter.label.dayofthemonth': 'Day of month',
  'counter.label.monthofyear': 'Month of year',
  'counter.label.interval': 'Interval',
  'counter.label.countertype': 'Counter Type',
  'counter.label.occurrence': 'Occurence',
  'counter.label.counteronvalue': 'Counter on value',
  'counter.label.monitoringendtype': 'Monitoring EndType',
  'counter.label.updatedby': 'Updated By',
  'counter.label.lastUpdateDate': 'Updated Date & Time',
  'counter.label.createdBy': 'Created By',
  'counter.label.createdDate': 'Created Time',
  'counter.label.status': 'Status',
  'counter.label.add': 'Add Counter',
  'counter.label.edit': 'Edit Counter',
  'counter.label.enddate': 'End Date',
  'counter.label.countonvalue': 'Unit',

  'counter.label.select.placeholder': 'Please Select',

  'counter.status.active': 'Active',
  'counter.status.inactive': 'Inactive',

  'counter.error.dayoftheweek': 'Please select day of the week',
  'counter.error.dayofthemonth': 'Please select day of the month',
  'counter.error.monthofyear': 'Please select month of the year',
  'counter.error.monitoringendtype': 'Please select monitoring end type',
  'counter.error.enddate': 'Please select End Date',
  'counter.error.name': 'Please enter valid Name',
  'counter.error.name.minimum': 'Minimum 2 character required',
  'counter.error.name.minimumone': 'Minimum 1 character required',
  'counter.error.name.maximum50': 'Maximum 50 character required',
  'counter.error.description': 'Please enter valid Description',
  'counter.error.description.minimum': 'Minimum 2 character required',
  'counter.error.description.maximum50': 'Maximum 200 character required',
  'counter.error.countertype': 'Please select valid counter type',
  'counter.error.countOn': 'Please select valid count on',
  'counter.error.unit': 'Please select Unit',
  'counter.error.onlynumber': 'Please enter numberic value',
  'counter.error.reset.type': 'Please select reset type',

  // Product
  'product.grid.view': 'View',
  'product.grid.srno': 'Sr. No.',
  'product.grid.name': 'Product Name',
  'product.grid.externalid': 'External ID',
  'product.grid.updateddatetime': 'Updated Date & Time',
  'product.grid.updatedby': 'Updated By',
  'product.grid.status': 'Status',

  // view label
  'product.success.add': 'Product Added Successfully',
  'product.success.edit': 'Product Updated Successfully',
  'product.success.delete': 'Product Deleted Successfully',

  'product.head.popup.add': 'Alert Add',
  'product.head.popup.edit': 'Update data',
  'product.head.popup.delete': 'Delete data',

  'product.delete.message': 'Are you sure, you want to delete this ?',
  'product.delete.confirm.message': 'Are you sure, You want to delete ?',
  'product.error.delete': 'Error occurred while deleting Product',

  'product.label.view': 'View',
  'product.label.name': 'Name',
  'product.label.externalid': 'External ID',
  'product.label.description': 'Description',
  'product.label.service': 'Service',
  'product.label.updatedby': 'Updated By',
  'product.label.lastUpdateDate': 'Updated Date & Time',
  'product.label.createdBy': 'Created By',
  'product.label.createdDate': 'Created Time',
  'product.label.status': 'Status',
  'product.label.add': 'Add Product',
  'product.label.edit': 'Edit Product',
  'product.label.enddate': 'End Date',

  'product.label.select.placeholder': 'Please Select',

  'product.status.active': 'Active',
  'product.status.inactive': 'Inactive',

  'product.error.service': 'Please select service',
  'product.error.name': 'Please enter valid Name',
  'product.error.name.minimum': 'Minimum 2 character required',
  'product.error.name.minimumone': 'Minimum 1 character required',
  'product.error.name.maximum50': 'Maximum 50 character required',
  'product.error.description': 'Please enter valid Description',
  'product.error.description.minimum': 'Minimum 2 character required',
  'product.error.description.maximum50': 'Maximum 50 character required',
  'product.error.description.maximum200': 'Maximum 200 character required',

  // Template notification
  'notificationTemplate.grid.view': 'View',
  'notificationTemplate.grid.srno': 'Sr. No.',
  'notificationTemplate.grid.name': 'Template Name',
  'notificationTemplate.grid.externalid': 'External ID',
  'notificationTemplate.grid.updateddatetime': 'Updated Date & Time',
  'notificationTemplate.grid.updatedby': 'Updated By',
  'notificationTemplate.grid.status': 'Status',

  // view label
  'notificationTemplate.success.add': 'Notification Template Added Successfully',
  'notificationTemplate.success.edit': 'Notification Template Updated Successfully',
  'notificationTemplate.success.delete': 'Notification Template Deleted Successfully',

  'notificationTemplate.head.popup.add': 'Alert Add',
  'notificationTemplate.head.popup.edit': 'Update data',
  'notificationTemplate.head.popup.delete': 'Delete data',

  'notificationTemplate.delete.message': 'Are you sure, you want to delete this ?',
  'notificationTemplate.delete.confirm.message': 'Are you sure, You want to delete ?',

  'notificationTemplate.label.view': 'View',
  'notificationTemplate.label.name': 'Name',
  'notificationTemplate.label.externalid': 'External ID',
  'notificationTemplate.label.template': 'Template',
  'notificationTemplate.label.updatedby': 'Updated By',
  'notificationTemplate.label.lastUpdateDate': 'Updated Date & Time',
  'notificationTemplate.label.createdBy': 'Created By',
  'notificationTemplate.label.createdDate': 'Created Time',
  'notificationTemplate.label.status': 'Status',
  'notificationTemplate.label.add': 'Add Notification Template',
  'notificationTemplate.label.edit': 'Edit Notification Template',
  'notificationTemplate.label.enddate': 'End Date',

  'notificationTemplate.label.select.placeholder': 'Please Select',

  'notificationTemplate.status.active': 'Active',
  'notificationTemplate.status.inactive': 'Inactive',

  'notificationTemplate.error.name': 'Please enter valid Name',
  'notificationTemplate.error.name.minimum': 'Minimum 2 character required',
  'notificationTemplate.error.name.minimumone': 'Minimum 1 character required',
  'notificationTemplate.error.name.maximum': 'Maximum 50 character required',
  'notificationTemplate.error.template': 'Please enter valid Template',
  'notificationTemplate.error.template.minimum': 'Minimum 2 character required',
  'notificationTemplate.error.template.maximum': 'Maximum 200 character required',

  // Notification
  'notification.label.add': 'Add',
  'notification.label.edit': 'Edit',
  'notification.label.view': 'View',
  'notification.label.srno': 'Sr No',
  'notification.label.name': 'Name',
  'notification.label.vendor': 'Vendor',
  'notification.label.vendorservice': 'Vendor Service',
  'notification.label.externalid': 'External ID',
  'notification.label.notificationtemplate': 'Notification Template',
  'notification.label.receiver': 'Receiver',
  'notification.label.receiveraddbtn': 'Add',
  'notification.label.receiverremovebtn': 'Remove',
  'notification.label.notificatontype': 'Notification Type',
  'notification.label.notificatontype1': 'SMS',
  'notification.label.notificatontype2': 'MOBILE',
  'notification.label.active': 'Active',
  'notification.label.inactive': 'Inactive',
  'notification.label.description': 'Description',
  'notification.label.updatedby': 'Updated By',
  'notification.label.updatedtime': 'Updated Time',
  'notification.label.createdby': 'Created By',
  'notification.label.createdtime': 'Created Time',
  'notification.label.status': 'Status',

  'notification.error.name': 'Please enter valid Name',
  'notification.error.name.minimum2': 'Please enter Name more than 2 character',
  'notification.error.name.maximum50': 'Please enter Name less thab 50 character',
  'notification.error.name.maximum200': 'Please enter Name less thab 200 character',
  'notification.error.description': 'Please enter valid description',
  'notification.error.notificationtype': 'Please select notification type',
  'notification.error.vendor': 'Please select vendor',
  'notification.error.vendorservice': 'Please select vendor service',
  'notification.error.notificationtmp': 'Please select notificatin template',
  'notification.success.add': 'Notification added successfully',
  'notification.success.edit': 'Notification updated successfully',
  'notification.success.delete': 'Notification deleted successfully',
  'notification.delete.confirm.message': 'Are you sure, You want to delete ?',
  'notification.fail.delete':
    'This Notification has been assigned more than one module, Please remove it and try again',

  // Common Error message do not change leave it at last
  'error.http.400': 'Something went wrong with submit request',
  'error.nameExists': 'Name already exists',
  NotNull: 'This filed is required',
  NotBlank: 'This filed is required',
  Min: 'Minimum character required',
  Max: 'Maximum character limit reached',
  nameExists: 'Name already exists',
  Size: 'Minimum or Maximum character limit not match',

  // Parameter

  'parameter.title.add': 'Add Paramater',
  'parameter.title.edit': 'Edit Paramater',

  'parameter.grid.view': 'View',
  'parameter.grid.srno': 'SR No.',
  'parameter.grid.name': 'Name',
  'parameter.grid.updatedby': 'Updated By',
  'parameter.grid.updatedtime': 'Updated Time',
  'parameter.grid.status': 'Status',
  'parameter.label.componenttype': 'Component Type',

  'parameter.placeholder.fieldtype': 'Please select field type',
  'parameter.label.name': 'Name',
  'parameter.label.fieldtype': 'Field Type',
  'parameter.label.description': 'Description',
  'parameter.label.credittype': 'Credit Type',
  'parameter.label.fieldtype1': 'Base',
  'parameter.label.fieldtype2': 'Aggregator',

  'parameter.label.componenttype1': 'Amount',
  'parameter.label.componenttype2': 'Unit',
  'parameter.label.componenttype3': 'Amount + Unit',
  'parameter.label.unit': 'Unit',
  'parameter.label.value': 'Value',
  'parameter.label.possiblevalue': 'Possible Value',
  'parameter.label.status': 'Status',
  'parameter.label.createdby': 'Created By',
  'parameter.label.createdtime': 'Created Time',
  'parameter.label.updatedby': 'Updated By',
  'parameter.label.updatedtime': 'Updated Time',
  'parameter.label.externalid': 'External ID',
  'parameter.status.active': 'Active',
  'parameter.status.inactive': 'Inactive',
  'parameter.label.childfield': 'Child Fields',
  'parameter.label.regex': 'Regex',
  'parameter.label.validationmessage': 'Validation Message',
  'parameter.label.datatype': 'Data Type',
  'parameter.label.childfiledname': 'Child field Information',
  'parameter.label.filedname': 'Select Filed Name',
  'parameter.label.mandatory': 'Is Mandatory',
  'parameter.label.editable': 'Is Editable',
  'parameter.label.editableby': 'Editable By',
  'parameter.label.checkerflow': 'Checker Flow',

  'parameter.error.name': 'Please enter valid name',
  'parameter.error.name.minimum2': 'Minimum 2 character required',
  'parameter.error.name.maximum50': 'Maximum 50 character allowed',
  'parameter.error.description.maximum200': 'Maximum 200 character allowed',
  'parameter.error.value.minimum2': 'Minimum 2 character required',
  'parameter.error.value.maximum20': 'Maximum 20 character allowed',
  'parameter.error.fieldtype': 'Field type is required',
  'parameter.error.credittype': 'Credit type is required',
  'parameter.error.unit': 'Unit is required',
  'parameter.error.value': 'Value is required',
  'parameter.error.childfield': 'Child Fields required',
  'parameter.error.description': 'Please enter valid description',
  'parameter.error.datatype': 'Please Select Datatype',
  'parameter.error.crediton': 'Credit on is required',
  'parameter.error.regex': 'Please enter valid regex',
  'parameter.error.validationmessage': 'Please enter valid validation message',
  'parameter.error.componenttype': 'Component type is required',
  'parameter.error.possiblevalue': 'Please enter valid description possible value',
  'parameter.delete.confirm.message': 'Are you sure, You want to delete ?',
  'parameter.success.add': 'Parameter added successfully',
  'parameter.success.edit': 'Parameter updated successfully',
  'parameter.success.delete': 'Parameter deleted successfully',
  'parameter.fail.delete':
    'This parameter has been assigned more than one module, Please remove it and try again',
  // Emoney
  'emoney.label.businesszone': 'Business Zone',
  'emoney.label.amount': 'Amount',
  'emoney.label.remark': 'Remark',
  'emoney.label.username': 'UserName',
  'emoney.label.pouch': 'Pouch',

  'emoney.error.businesszone': 'Please Select Business Zone!',
  'emoney.error.pouch': 'Please Select Pouch!',
  'emoney.error.amount': 'Please Enter valid Amount',
  'emoney.error.remark': 'Please Enter valid Remark',
  'emoney.error.username': 'Please Enter valid User Name',
  'emoney.label.select.placeholder': 'Please Select',

  // KYC
  'kyc.title.add': 'Add KYC',
  'kyc.title.edit': 'Edit KYC',
  'kyc.title.view': 'View KYC',

  'kyc.grid.view': 'View',
  'kyc.grid.srno': 'SR No.',
  'kyc.grid.name': 'Name',
  'kyc.grid.description': 'Description',
  'kyc.grid.updatedby': 'Updated By',
  'kyc.grid.updatedtime': 'Updated Time',
  'kyc.grid.status': 'Status',

  'kyc.label.name': 'Name',
  'kyc.label.description': 'Description',
  'kyc.label.status': 'Status',
  'kyc.label.createdby': 'Created By',
  'kyc.label.createdtime': 'Created Time',
  'kyc.label.updatedby': 'Updated By',
  'kyc.label.updatedtime': 'Updated Time',
  'kyc.label.externalid': 'External ID',
  'kyc.status.active': 'Active',
  'kyc.status.inactive': 'Inactive',
  'kyc.label.addbutton': 'Add',
  'kyc.label.levelNo': 'Level No',
  'kyc.label.levelName': 'Level Name',
  'kyc.label.levelField': 'Level Field',
  'kyc.label.kycfieldinfo': 'KYC Level Information',
  'kyc.error.name': 'Please Enter valid Name',
  'kyc.error.name.minimum': 'Minimum 2 character required',
  'kyc.error.name.maximum': 'Maximum 50 character allowed',
  'kyc.error.description': 'Please Enter valid Description',
  'kyc.error.description.minimum': 'Minimum 2 character required',
  'kyc.error.description.maximum': 'Maximum 200 character allowed',
  'kyc.error.levelname': 'Please Enter valid Level name',
  'kyc.error.levelname.minimum': 'Minimum 2 character required',
  'kyc.error.levelname.maximum': 'Maximum 50 character allowed',
  'kyc.error.levelfields': 'Please Select Level fields!',
  'kyc.label.srNo': 'Sr No.',

  'kyc.placeholder.levelfields': 'Select level fields',
  'kyc.delete.confirm.message': 'Are you sure, You want to delete ?',
  'kyc.error.delete': 'Error occurred while deleting KYC',
  'kyc.success.add': 'KYC added successfully',
  'kyc.success.edit': 'KYC updated successfully',
  'kyc.success.delete': 'KYC deleted successfully',
  'kyc.head.popup.delete': 'Delete data',
  'kyc.button.addkycfields': 'Select Level Fields',
  'kyc.label.levelfields': 'Level Fields',
  'kyc.label.levelfield': 'Level Field',
  'kyc.label.IsMandatory': 'Is Mandatory',
  'kyc.label.IsEditable': 'Is Editable',
  'kyc.label.remove': 'Remove',
  'kyc.label.button.addKycLevel': 'Add KYC Level',
  'kyc.label.button.addField': 'Add Field',
  'kyc.label.button.details': 'Details',

  'pouch.label.srno': 'Sr No.',
  'pouch.label.name': 'Name',
  'pouch.label.description': 'Description',
  'pouch.label.extrnalid': 'External ID',
  'pouch.label.view': 'View',
  'pouch.label.status': 'Status',
  'pouch.label.status.active': 'Active',
  'pouch.label.status.inactive': 'Inactive',
  'pouch.module.view': 'View Pouch',
  'pouch.module.edit': 'Edit Pouch',
  'pouch.label.createdby': 'Created By',
  'pouch.label.createdtime': 'Created Time',
  'pouch.label.updatedby': 'Updated By',
  'pouch.label.updatedtime': 'Updated Time',

  'pouch.error.name': 'Please enter valid name',
  'pouch.error.name.maximum50': 'Maximum 50 character allowed',
  'pouch.error.description.maximum200': 'Maximum 200 character allowed',
  'pouch.error.description.minimum': 'Minimum 2 character required',
  'pouch.error.description': 'Description',

  'pouch.success.add': 'Pouch added successfully',
  'pouch.success.edit': 'Pouch updated successfully',
  'pouch.success.delete': 'Pouch deleted successfully',
  'pouch.delete.confirm.message': 'Are you sure, You want to delete ?',
  'pouch.fail.delete':
    'This pouch has been assigned more than one module, Please remove it and try again',

  // Product group

  'productgroup.name': 'Name',
  'productgroup.label.add': 'Add Product Group',
  'productgroup.label.edit': 'Edit Product Group',
  'productgroup.label.view': 'View Product Group',
  'productgroup.description': 'Description',
  'productgroup.externalid': 'External ID',
  'productgroup.status': 'Status',
  'productgroup.label.createdby': 'Created By',
  'productgroup.label.createddatetime': 'Created Time',
  'productgroup.label.updatedby': 'Updated By',
  'productgroup.label.updateddatetime': 'Updated Time',
  'productgroup.status.active': 'Active',
  'productgroup.status.inactive': 'Inactive',
  'productgroup.label.product': 'Product',

  'productgroup.grid.srno': 'Sr. No.',
  'productgroup.grid.view': 'View',
  'productgroup.grid.id': 'ID',
  'productgroup.grid.name': 'Name',
  'productgroup.grid.description': 'Description',
  'productgroup.grid.externalid': 'External ID',
  'productgroup.grid.updatedby': 'Updated By',
  'productgroup.grid.updateddatetime': 'Updated Time',
  'productgroup.grid.status': 'Status',

  'productgroup.error.name.minimum': 'Minimum 2 character required',
  'productgroup.error.name.maximum50': 'Maximum 50 character required',
  'productgroup.error.name.maximum200': 'Maximum 200 character required',
  'productgroup.error.name': 'Please enter valid Name',
  'productgroup.error.description': 'Please enter valid Description',
  'productgroup.error.externalid': 'Please enter valid Externalid',
  'productgroup.error.status': 'Please enter valid Status',
  'productgroup.error.product': 'Please select valid Product',

  'productgroup.success.add': 'Product group Added Successfully',
  'productgroup.success.edit': 'Product group updated Successfully',
  'productgroup.success.delete': 'Product group deleted Successfully',
  'productgroup.delete.confirm.message': 'Are you sure, You want to delete ?',
  'productgroup.head.popup.add': 'Alert Add',
  'productgroup.head.popup.edit': 'Update data',
  'productgroup.head.popup.delete': 'Delete data',
  'productgroup.fail.delete':
    'This productgroup has been assigned more than one module, Please remove it and try again',

  'businessentity.name': 'Name',
  'businessentity.label.add': 'Add Business Entity',
  'businessentity.label.edit': 'Edit Business Entity',
  'businessentity.label.view': 'View Business Entity',
  'businessentity.description': 'Description',
  'businessentity.externalid': 'External ID',
  'businessentity.status': 'Status',
  'businessentity.label.createdby': 'Created By',
  'businessentity.label.createddatetime': 'Created Time',
  'businessentity.label.updatedby': 'Updated By',
  'businessentity.label.updateddatetime': 'Updated Time',
  'businessentity.label.usercategory': 'User Category',
  'businessentity.label.pouch': 'Pouch',
  'businessentity.label.currency': 'Currency',
  'businessentity.label.businesszone': 'Business Zone',
  'businessentity.label.kyc': 'KYC',
  'businessentity.label.kyclevel': 'KYC Level',
  'businessentity.label.serviceprofile': 'Service Profile',
  'buisnessentity.label.services': 'Services',
  'buisnessentity.label.serviceaddbtn': 'Add Services',
  'businessentity.label.services': 'Services',
  'businessentity.label.trustaccount': 'Trust Account',
  'businessentity.label.regularaccount': 'Regular Account',
  'businessentity.status.active': 'Active',
  'businessentity.status.inactive': 'Inactive',
  'businessentity.label.srno': 'Sr no.',
  'businessentity.label.selectservices': 'Select Services',
  'businessentity.label.selectaccount': 'Select Account',
  'businessentity.label.addservices': 'Services',

  'businessentity.grid.srno': 'Sr. No.',
  'businessentity.grid.view': 'View',
  'businessentity.grid.id': 'ID',
  'businessentity.grid.name': 'Name',
  'businessentity.grid.description': 'Description',
  'businessentity.grid.externalid': 'External ID',
  'businessentity.grid.updatedby': 'Updated By',
  'businessentity.grid.updateddatetime': 'Updated Time',
  'businessentity.grid.status': 'Status',

  'businessentity.error.name.minimum': 'Minimum 2 character required',
  'businessentity.error.name.maximum50': 'Maximum 50 character required',
  'businessentity.error.name.maximum200': 'Maximum 200 character required',
  'businessentity.error.name': 'Please enter valid Name',
  'businessentity.error.description': 'Please enter valid Description',
  'businessentity.error.externalid': 'Please enter valid Externalid',
  'businessentity.error.status': 'Please enter valid Status',
  'businessentity.error.usercategory': 'Please select user category',
  'businessentity.error.currency': 'Please select user currency',
  'businessentity.error.businesszone': 'Please select business zone',
  'businessentity.error.kyc': 'Please select KYC',
  'businessentity.error.kyclevel': 'Please select KYC Level',
  'businessentity.error.serviceprofile': 'Please select service profile',
  'businessentity.error.services': 'Please select services',
  'businessentity.error.accounttypechkbox': 'Please select account type',
  'businessentity.error.regularaccount': 'Please select regular account',
  'businessentity.error.pouch': 'Please select pouch',
  'businessentity.error.trustaccount': 'Please select trust account',

  'businessentity.success.add': 'Business Entity Added Successfully',
  'businessentity.success.edit': 'Business Entity updated Successfully',
  'businessentity.success.delete': 'Business Entity deleted Successfully',
  'businessentity.fail.delete':
    'This Business Entity has been assigned more than one module, Please remove it and try again',
  'businessentity.delete.confirm.message': 'Are you sure, You want to delete ?',
  'businessentity.head.popup.add': 'Alert Add',
  'businessentity.head.popup.edit': 'Update data',
  'businessentity.head.popup.delete': 'Delete data',

  // Wallet constants
  'wallet.grid.srno': 'Sr. No.',
  'wallet.grid.view': 'View',
  'wallet.grid.id': 'ID',
  'wallet.grid.name': 'Name',
  'wallet.grid.externalid': 'External ID',
  'wallet.grid.wallettype': 'Wallet Type',
  'wallet.grid.updateddate': 'Updated Date',
  'wallet.grid.updatedby': 'Updated By',
  'wallet.grid.status': 'Status',
  'wallet.label.view': 'View Wallet',

  'wallet.name': 'Name',
  'wallet.externalid': 'External ID',
  'wallet.status': 'Status',
  'wallet.status.active': 'Active',
  'wallet.status.inactive': 'Inactive',
  'wallet.description': 'Description',
  'wallet.behaviour': 'Behaviour',
  'wallet.wallettype': 'Wallet Type',
  'wallet.wallettype.trustaccount': 'Trust Account',
  'wallet.wallettype.regular': 'Regular',

  'wallet.createdBy': 'Created By',
  'wallet.createdDate': 'Created Time',
  'wallet.updatedBy': 'Updated By',
  'wallet.updatedDate': 'Updated Time',

  'wallet.success.add': 'Wallet Added Successfully',
  'wallet.success.edit': 'Wallet updated Successfully',
  'wallet.success.delete': 'Wallet deleted Successfully',
  'wallet.delete.message': 'Are you sure you want to delete this?',
  'wallet.head.popup.add': 'Alert Add',
  'wallet.head.popup.edit': 'Update data',
  'wallet.head.popup.delete': 'Delete data',

  'wallet.error.name.minimum': 'Minimum 2 character required',
  'wallet.error.name.maximum50': 'Maximum 50 character required',
  'wallet.error.name.maximum200': 'Maximum 200 character required',

  'wallet.error.description.minimum': 'Minimum 2 character required',
  'wallet.error.description.maximum50': 'Maximum 50 character required',
  'wallet.error.description.maximum200': 'Maximum 200 character required',

  'wallet.error.name': 'Please Input Name',
  'wallet.error.description': 'Please Input Description',
  'wallet.error.externalid': 'Please Input Externalid',
  'wallet.error.status': 'Please Input Status',
  'wallet.error.wallettype': 'Please Select Wallet Type',
  'wallet.error.behaviour': 'Please Select Behaviour',

  // Product Management
  'productmanagement.label.srno': 'Sr. No.',
  'productmanagement.label.vendor': 'Vendor Name',
  'productmanagement.label.extrnalid': 'External ID',
  'productmanagement.label.vendorservice': 'Vendor Service',
  'productmanagement.label.updatedby': 'Updated By',
  'productmanagement.label.updatedtime': 'Updated Time',
  'productmanagement.label.createdby': 'Created By',
  'productmanagement.label.createdtime': 'Created Time',
  'productmanagement.label.status': 'Status',
  'productmanagement.label.active': 'Active',
  'productmanagement.label.inactive': 'Inactive',
  'productmanagement.label.grid.view': 'View',
  'productmanagement.label.view': 'View Product Management',
  'productmanagement.label.edit': 'Edit Product Management',
  'productmanagement.error.vendorservice': 'Please select vendor service',
  'productmanagement.error.vendor': 'Please select vendor',

  'productmanagement.success.edit': 'Product Management updated successfully',
  'productmanagement.delete.confirm.message': 'Are you sure, You want to delete ?',
  'productmanagement.success.delete': 'Product Management deleted successfully',
  'productmanagement.fail.delete': 'Fail to delete',

  // Technical Vendor
  'technicalvendor.name': 'Name',
  'technicalvendor.vendorservice': 'Vendor Service',
  'technicalvendor.apiContextPath': 'API Context Path',
  'technicalvendor.apiUrl': 'API Url',
  'technicalvendor.host': 'Host',
  'technicalvendor.port': 'Port',
  'technicalvendor.httpProtocol': 'HttpProtocol',
  'technicalvendor.httpType': 'HttpType',
  'technicalvendor.requestType': 'RequestType',
  'technicalvendor.retryCount': 'RetryCount',
  'technicalvendor.timeout': 'TimeOut',
  'technicalvendor.successCode': 'SuccessCodes',
  'technicalvendor.failureCode': 'FailureCodes',
  'technicalvendor.apiTemplate': 'API Template',
  'technicalvendor.apiField': 'API Field',
  'technicalvendor.mobifinpacketfield': 'Mobifin Packet Field',
  'technicalvendor.externalid': 'External ID',
  'technicalvendor.status': 'Status',
  'technicalvendor.status.active': 'Active',
  'technicalvendor.status.inactive': 'Inactive',
  'technicalvendor.label.view': 'View Services',
  'technicalvendor.label.edit': 'Edit Services',

  'technicalvendor.createdBy': 'Created By',
  'technicalvendor.createdDate': 'Created Time',
  'technicalvendor.updatedBy': 'Updated By',
  'technicalvendor.updatedDate': 'Updated Time',

  'technicalvendor.grid.view': 'View',
  'technicalvendor.grid.srno': 'Sr No.',
  'technicalvendor.grid.name': 'Name',
  'technicalvendor.grid.description': 'Description',
  'technicalvendor.grid.externalid': 'External ID',
  'technicalvendor.grid.createdDate': 'Created Date',
  'technicalvendor.grid.updatedDate': 'Updated Date',
  'technicalvendor.grid.validFromDate': 'Valid From Date',
  'technicalvendor.grid.validToDate': 'Valid To Date',
  'technicalvendor.grid.lastUpdateDate': 'Updated Time',
  'technicalvendor.grid.updatedBy': 'Updated By',
  'technicalvendor.grid.status': 'Status',

  'technicalvendor.error.name': 'Please enter valid Name.',
  'technicalvendor.error.name.minsize': 'Minimum 2 character required ',
  'technicalvendor.error.name.maxsize': 'Maximum 50 character required',
  'technicalvendor.error.apiContextPath': 'Please enter valid ApiContext Path',
  'technicalvendor.error.apiContextPath.minimum': 'Minimum 2 character required ',
  'technicalvendor.error.apiContextPath.maximum50': 'Maximum 50 character required',
  'technicalvendor.error.host': 'Please enter valid Host',
  'technicalvendor.error.host.minimum': 'Minimum 2 character required ',
  'technicalvendor.error.host.maximum50': 'Maximum 50 character required',
  'technicalvendor.error.port': 'Please enter valid Port',
  'technicalvendor.error.port.minimum': 'Minimum 2 character required ',
  'technicalvendor.error.port.maximum50': 'Maximum 50 character required',
  'technicalvendor.error.httpProtocol': 'Please Select valid Http Protocol',
  'technicalvendor.error.httpType': 'Please Select valid Http Type',
  'technicalvendor.error.successCode': 'Please enter valid Success Code',
  'technicalvendor.error.successCode.minimum': 'Minimum 2 character required ',
  'technicalvendor.error.successCode.maximum50': 'Maximum 50 character required',
  'technicalvendor.error.failureCode': 'Please enter valid Failure Code',
  'technicalvendor.error.failureCode.minimum': 'Minimum 2 character required ',
  'technicalvendor.error.failureCode.maximum50': 'Maximum 50 character required',
  'technicalvendor.error.apiTemplate': 'Please enter valid API Template',
  'technicalvendor.error.apiTemplate.minsize': 'Minimum 2 character required',
  'technicalvendor.error.apiTemplate.maxsize': 'Maximum 200 character required',
  'technicalvendor.error.headerMapping.ApiField': "Please input Api's field.",
  'technicalvendor.error.headerMapping.MobifinPacketField': 'Please input MobifinPacket field.',
  'technicalvendor.error.requestMapping.ApiField': "Please input Api's field.",
  'technicalvendor.error.requestMapping.MobifinPacketField': 'Please input MobifinPacket field.',
  'technicalvendor.error.responseMapping.ApiField': "Please input Api's field.",
  'technicalvendor.error.responseMapping.MobifinPacketField': 'Please input MobifinPacket field.',
  'technicalvendor.error.externalid': 'Please enter valid Externalid',
  'technicalvendor.error.status': 'Please Input Status',
  'technicalvendor.error.vendorservice': 'Please select vendor service',
  'technicalvendor.error.name.minimum': 'Minimum 2 character required',

  'technicalvendor.delete.message': 'Are you sure, you want to delete this ?',
  'technicalvendor.success.add': 'Technical Vendor Added Successfully',
  'technicalvendor.success.edit': 'Technical Vendor Updated Successfully',
  'technicalvendor.success.delete': 'Technical Venodr Deleted Successfully',
  'technicalvendor.head.popup.add': 'Alert Add',
  'technicalvendor.head.popup.edit': 'Update data',
  'technicalvendor.head.popup.delete': 'Delete data',
  'technicalvendor.label.add': 'Add Technical Vendor',
  'technicalvendor.label.name': 'Name',
  'technicalvendor.id': 'Id',
  'technicalvendor.defaultValue': 'Default Value',
  'technicalvendor.validation.submit.error': 'Please select the Previous button and fill the form',
  'technicalvendor.error.responseMapping.ResponseSection': 'Please Fill up the Response Section',
  'technicalvendor.error.menditory': 'Please fill up all the mandatory field',

  // Services Vendor
  'servicevendor.name': 'Name',
  'servicevendor.label.name': 'Name',
  'servicevendor.vendorservice': 'Vendor Service',
  'servicevendor.apiUrl': 'API Url',
  'servicevendor.httpProtocol': 'HttpProtocol',
  'servicevendor.httpType': 'HttpType',
  'servicevendor.requestType': 'RequestType',
  'servicevendor.retryCount': 'RetryCount',
  'servicevendor.timeout': 'TimeOut',
  'servicevendor.successCode': 'SuccessCodes',
  'servicevendor.failureCode': 'FailureCodes',
  'servicevendor.apiTemplate': 'API Template',
  'servicevendor.apiField': 'API Field',
  'servicevendor.mobifinpacketfield': 'Mobifin Packet Field',
  'servicevendor.externalid': 'External ID',
  'servicevendor.status': 'Status',
  'servicevendor.status.active': 'Active',
  'servicevendor.status.inactive': 'Inactive',
  'servicevendor.label.view': 'View Services',
  'servicevendor.label.edit': 'Edit Services',

  'servicevendor.createdBy': 'Created By',
  'servicevendor.createdDate': 'Created Time',
  'servicevendor.updatedBy': 'Updated By',
  'servicevendor.updatedDate': 'Updated Time',

  'servicevendor.grid.view': 'View',
  'servicevendor.grid.srno': 'Sr No.',
  'servicevendor.grid.name': 'Name',
  'servicevendor.grid.description': 'Description',
  'servicevendor.grid.externalid': 'External ID',
  'servicevendor.grid.createdDate': 'Created Date',
  'servicevendor.grid.updatedDate': 'Updated Date',
  'servicevendor.grid.validFromDate': 'Valid From Date',
  'servicevendor.grid.validToDate': 'Valid To Date',
  'servicevendor.grid.lastUpdateDate': 'Updated Time',
  'servicevendor.grid.updatedBy': 'Updated By',
  'servicevendor.grid.status': 'Status',

  'servicevendor.error.name': 'Please enter valid Name.',
  'servicevendor.error.name.minsize': 'Minimum 2 character required ',
  'servicevendor.error.name.maxsize': 'Maximum 50 character required',
  'servicevendor.error.apiUrl': 'Please enter valid Api URl',
  'servicevendor.error.apiUrl.minimum': 'Minimum 2 character required ',
  'servicevendor.error.apiUrl.maximum50': 'Maximum 50 character required',
  'servicevendor.error.httpProtocol': 'Please Select valid Http Protocol',
  'servicevendor.error.httpType': 'Please Select valid Http Type',
  'servicevendor.error.successCode': 'Please enter valid Success Code',
  'servicevendor.error.successCode.minimum': 'Minimum 2 character required ',
  'servicevendor.error.successCode.maximum50': 'Maximum 50 character required',
  'servicevendor.error.failureCode': 'Please enter valid Failure Code',
  'servicevendor.error.failureCode.minimum': 'Minimum 2 character required ',
  'servicevendor.error.failureCode.maximum50': 'Maximum 50 character required',
  'servicevendor.error.apiTemplate': 'Please enter valid API Template',
  'servicevendor.error.apiTemplate.minsize': 'Minimum 2 character required',
  'servicevendor.error.apiTemplate.maxsize': 'Maximum 200 character required',
  'servicevendor.error.headerMapping.ApiField': "Please input Api's field.",
  'servicevendor.error.headerMapping.MobifinPacketField': 'Please input MobifinPacket field.',
  'servicevendor.error.requestMapping.ApiField': "Please input Api's field.",
  'servicevendor.error.requestMapping.MobifinPacketField': 'Please input MobifinPacket field.',
  'servicevendor.error.responseMapping.ApiField': "Please input Api's field.",
  'servicevendor.error.responseMapping.MobifinPacketField': 'Please input MobifinPacket field.',
  'servicevendor.error.responseMapping.ResponseSection': 'Please Fill up the Response Section',
  'servicevendor.error.menditory': 'Please fill up all the mandatory field',
  'servicevendor.error.externalid': 'Please enter valid Externalid',
  'servicevendor.error.status': 'Please Input Status',
  'servicevendor.delete.message': 'Are you sure, you want to delete this ?',
  'servicevendor.success.add': 'Service Vendor Added Successfully',
  'servicevendor.success.edit': 'Service Vendor updated Successfully',
  'servicevendor.success.delete': 'Service Vendor deleted Successfully',
  'servicevendor.head.popup.add': 'Alert Add',
  'servicevendor.head.popup.edit': 'Update data',
  'servicevendor.head.popup.delete': 'Delete data',
  'servicevendor.label.add': 'Add Service Vendor',
  'servicevendor.id': 'Id',
  'servicevendor.defaultValue': 'Default Value',
  'servicevendor.error.name.minimum': 'Minimum 2 character required',
  'servicevendor.error.vendorservice': 'Please select vendor service',

  // OnBoarding
  'onboarding.label.add': 'Add On Boading',
  'onboarding.label.businessentity': 'Business Entity',
  'onboarding.label.select.placeholder': 'Please select',

  'onboarding.error.businessentity': 'Please enter valid business entity',

  // Exchange rate manager
  'exchangerate.title.add': 'Add Currency Exchange Rate',
  'exchangerate.title.edit': 'Edit Currency Exchange Rate',

  'exchangerate.grid.view': 'View',
  'exchangerate.grid.srno': 'SR No.',
  'exchangerate.grid.fromcurrency': 'From Currency',
  'exchangerate.grid.tocurrency': 'To Currency',
  'exchangerate.grid.exchangerate': 'Exchange Rate',
  'exchangerate.grid.validfromdate': 'Valid From Date',
  'exchangerate.grid.validtodate': 'Valid To Date',
  'exchangerate.grid.updatedby': 'Updated By',
  'exchangerate.grid.updatedtime': 'Updated Time',
  'exchangerate.grid.status': 'Status',

  'exchangerate.label.fromcurrency': 'From Currency',
  'exchangerate.label.tocurrency': 'To Currency',
  'exchangerate.label.exchangerate': 'Exchange Rate',
  'exchangerate.label.validfromdate': 'Valid From Date',
  'exchangerate.label.validtodate': 'Valid To Date',
  'exchangerate.label.status': 'Status',
  'exchangerate.label.createdby': 'Created By',
  'exchangerate.label.createdtime': 'Created Time',
  'exchangerate.label.updatedby': 'Updated By',
  'exchangerate.label.updatedtime': 'Updated Time',
  'exchangerate.label.externalid': 'External ID',
  'exchangerate.status.active': 'Active',
  'exchangerate.status.inactive': 'Inactive',
  'exchangerate.placeholder.fromcurrency': 'Please Select',
  'exchangerate.placeholder.tocurrency': 'Please Select',

  'exchangerate.error.fromcurrency': 'Please select From Currency',
  'exchangerate.error.tocurrency': 'Please select To Currency',
  'exchangerate.error.exchangerate': 'Please select Exchangerate',
  'exchangerate.error.validfromdate': 'Please select valid from date',
  'exchangerate.error.validtodate': 'Please select valid to date',
  'exchangerate.success.add': 'Exchangerate added successfully',
  'exchangerate.success.edit': 'Exchangerate updated successfully',
  'exchangerate.delete.confirm.message': 'Are you sure, You want to delete ?',
  'exchangerate.success.delete': 'Exchangerate deleted successfully',
  'exchangeratemanager.error.delete': 'Error occurred while deleting Exchange rate',
  'exchangerate.fail.delete': 'Fail to delete',
  'exchangerate.error.CurrencyNotSame': 'From Currency and To Currency should not be same!',
  'exchangerate.error.DateNotSame': 'From Date and To Date should not be same',
  'exchangerate.head.popup.add': 'Alert Add',
  'exchangerate.head.popup.edit': 'Update data',
  'exchangerate.head.popup.delete': 'Delete data',

  // Service Profile
  'serviceprofile.grid.srno': 'Sr. No.',
  'serviceprofile.grid.view': 'View',
  'serviceprofile.grid.name': 'Name',
  'serviceprofile.grid.updatedby': 'Updated By',
  'serviceprofile.grid.updateddatetime': 'Updated Time',
  'serviceprofile.label.status': 'Status',

  'serviceprofile.search.name': 'Name',
  'serviceprofile.tree.name': 'Service Profile Tree',
  'serviceprofile.tree.selection': 'Please select Entity',

  'serviceprofile.name': 'Name',
  'serviceprofile.error.name': 'Please enter valid Name',
  'serviceprofile.error.name.minimum': 'Minimum 2 character required',
  'serviceprofile.error.name.maximum50': 'Maximum 50 character required',
  'serviceprofile.error.name.maximum200': 'Maximum 200 character required',
  'serviceprofile.description': 'Description',
  'serviceprofile.error.description': 'Please enter valid Description',

  'serviceprofile.success.add': 'Service Profile  Added Successfully',
  'serviceprofile.success.edit': 'Service Profile updated Successfully',
  'serviceprofile.success.delete': 'Service Profile deleted Successfully',
  'serviceprofile.delete.confirm.message': 'Are you sure, You want to delete ?',
  'serviceprofile.head.popup.add': 'Alert Add',
  'serviceprofile.head.popup.edit': 'Update data',
  'serviceprofile.head.popup.delete': 'Delete data',
  'serviceprofile.label.add': 'Add',
  'serviceprofile.status': 'Status',
  'serviceprofile.status.active': 'Active',
  'serviceprofile.status.inactive': 'Inactive',
  'serviceprofile.label.view': 'Service profile view',
  'serviceprofile.label.lastUpdateDate': 'Updated Time',
  'serviceprofile.label.updatedby': 'Updated By',
  'serviceprofile.label.createdDate': 'Created Time',
  'serviceprofile.label.createdBy': 'Created By',
  'serviceprofile.error.delete': 'Error occured while deleting service profile',
  'serviceprofile.label.edit': 'Edit',

  // Business Zone
  'businesszone.grid.view': 'View',
  'businesszone.grid.srno': 'Sr.No',
  'businesszone.grid.name': 'Name',
  'businesszone.grid.externalid': 'External ID',
  'businesszone.grid.updatedby': 'Updated By',
  'businesszone.grid.updateddatetime': 'Updated Time',
  'businesszone.grid.status': 'Status',
  'businesszone.label.add': 'Add',
  'businesszone.label.name': 'Name',
  'businesszone.error.name': 'Please enter valid name',
  'businesszone.error.name.minimum': 'Minimum 2 character required',
  'businesszone.error.name.maximum50': 'Maximum 50 character required',
  'businesszone.label.status': 'Status',
  'businesszone.status.active': 'Active',
  'businesszone.status.inactive': 'Inactive',
  'businesszone.success.add': 'Business zone  Added Successfully',
  'businesszone.head.popup.add': 'Alert Add',
  'businesszone.success.edit': 'Business zone updated Successfully',
  'businesszone.head.popup.edit': 'Update Data',
  'businesszone.label.edit': 'Edit',
  'businesszone.delete.confirm.message': 'Are you sure, You want to delete ?',
  'businesszone.success.delete': 'Business zone deleted Successfully',
  'businesszone.label.view': 'View Business Zone',

  // systemoperatorentity
  'systemoperatorentity.label.srno': 'Sr No.',
  'systemoperatorentity.label.name': 'Name',
  'systemoperatorentity.label.description': 'Description',
  'systemoperatorentity.label.extrnalid': 'External ID',
  'systemoperatorentity.label.view': 'View',
  'systemoperatorentity.label.status': 'Status',
  'systemoperatorentity.label.status.active': 'Active',
  'systemoperatorentity.label.status.inactive': 'Inactive',
  'systemoperatorentity.module.view': 'View System Operator Entity',
  'systemoperatorentity.module.edit': 'Edit System Operator Entity',
  'systemoperatorentity.label.createdby': 'Created By',
  'systemoperatorentity.label.createdtime': 'Created Time',
  'systemoperatorentity.label.updatedby': 'Updated By',
  'systemoperatorentity.label.updatedtime': 'Updated Time',
  'systemoperatorentity.label.usercategory': 'User Category',
  'systemoperatorentity.label.kyclevel': 'KYC Level',
  'systemoperatorentity.label.role': 'Role',

  'systemoperatorentity.error.name': 'Please enter valid name',
  'systemoperatorentity.error.name.maximum50': 'Maximum 50 character allowed',
  'systemoperatorentity.error.description.maximum200': 'Maximum 200 character allowed',
  'systemoperatorentity.error.description.minimum': 'Minimum 2 character required',
  'systemoperatorentity.error.description': 'Description',
  'systemoperatorentity.error.usercategory': 'Please select user category',
  'systemoperatorentity.error.kyclevel': 'Please select kyc level',
  'systemoperatorentity.error.role': 'Please select kyc role',

  'systemoperatorentity.success.add': 'System Operator Entity added successfully',
  'systemoperatorentity.success.edit': 'System Operator Entity updated successfully',
  'systemoperatorentity.success.delete': 'System Operator Entity deleted successfully',
  'systemoperatorentity.delete.confirm.message': 'Are you sure, You want to delete ?',
  'systemoperatorentity.error.delete':
    'This system operator entity has been assigned more than one module, Please remove it and try again'
}
export default {
  locale: 'en-US',
  antdData,
  localeData,
  messages
}
